# Generated by Django 5.0.6 on 2024-06-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_avatar_user_bio_user_branch_user_name_user_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
    ]
