# Generated by Django 5.0.6 on 2024-06-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_upload_options_upload_created_upload_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Photo',
            field=models.FileField(default='None', upload_to=''),
        ),
    ]
