# Generated by Django 5.0.6 on 2024-06-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_room_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Photo',
            field=models.FileField(default='None', null=True, upload_to=''),
        ),
    ]
